In [1]:
%matplotlib inline
import numpy as np # linear algebra
import pandas as pd
# data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import pprint

import requests

sns.set_style('ticks')

In [2]:
import netCDF4
import xarray

In [3]:
elevation = netCDF4.Dataset('../data/gefs_elevations.nc', 'r')

In [4]:
elevation.variables

OrderedDict([('elevation_control', <class 'netCDF4._netCDF4.Variable'>
              float32 elevation_control(lat, lon)
                  units: m
              unlimited dimensions: 
              current shape = (9, 16)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('elevation_perturbation', <class 'netCDF4._netCDF4.Variable'>
              float32 elevation_perturbation(lat, lon)
                  units: m
              unlimited dimensions: 
              current shape = (9, 16)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('latitude', <class 'netCDF4._netCDF4.Variable'>
              float32 latitude(lat, lon)
              unlimited dimensions: 
              current shape = (9, 16)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('longitude', <class 'netCDF4._netCDF4.Variable'>
              float32 longitude(lat, lon)
              unlimited dimens

In [5]:
elevation.groups

OrderedDict()

In [6]:
elevation.dimensions

OrderedDict([('lon',
              <class 'netCDF4._netCDF4.Dimension'>: name = 'lon', size = 16),
             ('lat',
              <class 'netCDF4._netCDF4.Dimension'>: name = 'lat', size = 9)])

In [7]:
elevation.variables['longitude']

<class 'netCDF4._netCDF4.Variable'>
float32 longitude(lat, lon)
unlimited dimensions: 
current shape = (9, 16)
filling on, default _FillValue of 9.969209968386869e+36 used

In [8]:
longitudes = np.array(elevation.variables['longitude'])
latitudes = np.array(elevation.variables['latitude'])

In [9]:
np.array(elevation.variables['elevation_control'])

array([[1420.6992  , 1346.99    , 1323.4714  ,  878.6121  ,  801.2428  ,
         772.9914  ,  680.35266 ,  468.4641  ,  336.59415 ,  120.04214 ,
          93.48233 ,   80.08353 ,   71.31673 ,   67.957   ,   10.965302,
          84.810104],
       [1474.9441  , 1352.801   ,  898.3811  ,  931.03394 ,  826.7518  ,
         727.6931  ,  609.3953  ,  482.50412 ,  337.76724 ,  183.77028 ,
         102.97228 ,  126.72296 ,   79.13975 ,   45.891365,   33.39725 ,
          45.70796 ],
       [1580.3839  , 1424.2161  , 1176.4006  , 1125.1444  ,  948.3373  ,
         705.66315 ,  500.02255 ,  368.81665 ,  315.66757 ,  163.46469 ,
         154.10419 ,  121.9053  ,   75.232796,   77.09505 ,   30.765553,
          26.19909 ],
       [1893.4783  , 1518.9108  , 1275.5542  , 1200.2124  , 1043.7601  ,
         853.4426  ,  502.6673  ,  344.78058 ,  267.40408 ,  229.86818 ,
         159.78786 ,  141.98071 ,  131.23152 ,   71.77977 ,   69.824265,
          45.698303],
       [2056.1182  , 1627.2682  , 14

In [10]:
elevation.variables.values()

odict_values([<class 'netCDF4._netCDF4.Variable'>
float32 elevation_control(lat, lon)
    units: m
unlimited dimensions: 
current shape = (9, 16)
filling on, default _FillValue of 9.969209968386869e+36 used
, <class 'netCDF4._netCDF4.Variable'>
float32 elevation_perturbation(lat, lon)
    units: m
unlimited dimensions: 
current shape = (9, 16)
filling on, default _FillValue of 9.969209968386869e+36 used
, <class 'netCDF4._netCDF4.Variable'>
float32 latitude(lat, lon)
unlimited dimensions: 
current shape = (9, 16)
filling on, default _FillValue of 9.969209968386869e+36 used
, <class 'netCDF4._netCDF4.Variable'>
float32 longitude(lat, lon)
unlimited dimensions: 
current shape = (9, 16)
filling on, default _FillValue of 9.969209968386869e+36 used
])

In [11]:
np.array(elevation.variables['elevation_perturbation'])

array([[1342.6183  , 1328.494   , 1244.2654  ,  919.84937 ,  821.09357 ,
         758.44745 ,  615.6434  ,  470.27423 ,  320.5994  ,  140.99059 ,
          95.808876,   76.55379 ,   68.223305,   54.34377 ,   17.772333,
          68.332054],
       [1378.9469  , 1413.0527  , 1016.23267 ,  901.5925  ,  857.84326 ,
         718.2812  ,  608.256   ,  486.92395 ,  339.53586 ,  164.36885 ,
         117.53571 ,  116.33904 ,   77.80599 ,   61.09258 ,   23.557766,
          55.404343],
       [1742.8295  , 1598.1471  , 1091.235   , 1178.5747  ,  909.0582  ,
         734.5154  ,  526.7806  ,  401.44186 ,  306.54337 ,  199.78694 ,
         154.20181 ,  114.92896 ,   67.07196 ,   64.64995 ,   41.842697,
          25.231009],
       [1917.6676  , 1581.5814  , 1253.4536  , 1266.1656  , 1054.5192  ,
         810.1943  ,  486.44327 ,  356.4528  ,  293.86646 ,  243.86433 ,
         176.02136 ,  179.50739 ,  181.33006 ,  103.31555 ,   63.461838,
          43.063847],
       [1943.1647  , 1737.1079  , 13

In [12]:
latitudes

array([[31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31., 31.,
        31., 31., 31.],
       [32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32., 32.,
        32., 32., 32.],
       [33., 33., 33., 33., 33., 33., 33., 33., 33., 33., 33., 33., 33.,
        33., 33., 33.],
       [34., 34., 34., 34., 34., 34., 34., 34., 34., 34., 34., 34., 34.,
        34., 34., 34.],
       [35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35., 35.,
        35., 35., 35.],
       [36., 36., 36., 36., 36., 36., 36., 36., 36., 36., 36., 36., 36.,
        36., 36., 36.],
       [37., 37., 37., 37., 37., 37., 37., 37., 37., 37., 37., 37., 37.,
        37., 37., 37.],
       [38., 38., 38., 38., 38., 38., 38., 38., 38., 38., 38., 38., 38.,
        38., 38., 38.],
       [39., 39., 39., 39., 39., 39., 39., 39., 39., 39., 39., 39., 39.,
        39., 39., 39.]], dtype=float32)

## Create DataFrame out of geography data
I will need to look at the other data types and see how to combine them all together.

Latitude and Longitude could be used as a MultiIndex, at least for this dataset.

In [13]:
def netcdf4_to_dataframe(netcdf):
    data_as_array = np.array([np.array(i).flatten() for i in netcdf.variables.values()]).T
    data_as_dataframe = pd.DataFrame(data_as_array, columns=netcdf.variables.keys())
    return data_as_dataframe
    

In [14]:
netcdf4_to_dataframe(elevation)

elevation_control  elevation_perturbation  latitude  longitude
0          1420.699219             1342.618286      31.0      254.0
1          1346.989990             1328.494019      31.0      255.0
2          1323.471436             1244.265381      31.0      256.0
3           878.612122              919.849365      31.0      257.0
4           801.242798              821.093567      31.0      258.0
5           772.991394              758.447449      31.0      259.0
6           680.352661              615.643372      31.0      260.0
7           468.464111              470.274231      31.0      261.0
8           336.594147              320.599396      31.0      262.0
9           120.042137              140.990585      31.0      263.0
10           93.482330               95.808876      31.0      264.0
11           80.083527               76.553787      31.0      265.0
12           71.316727               68.223305      31.0      266.0
13           67.957001               54.343769      31.0      267.0
14           10.965302               17.772333      31.0      268.0
15           84.810104               68.332054      31.0      269.0
16         1474.944092             1378.946899      32.0      254.0
17         1352.801025             1413.052734      32.0      255.0
18          898.381104             1016.232666      32.0      256.0
19          931.033936              901.592529      32.0      257.0
20          826.751770              857.843262      32.0      258.0
21          727.693115              718.281189      32.0      259.0
22          609.395325              608.255981      32.0      260.0
23          482.504120              486.923950      32.0      261.0
24          337.767242              339.535858      32.0      262.0
25          183.770279              164.368851      32.0      263.0
26          102.972282              117.535713      32.0      264.0
27          126.722961              116.339043      32.0      265.0
28           79.139748               77.805992      32.0      266.0
29           45.891365               61.092579      32.0      267.0
..                 ...                     ...       ...        ...
114        1390.321289             1397.668945      38.0      256.0
115        1225.845215             1258.560547      38.0      257.0
116        1073.791382             1109.736816      38.0      258.0
117         897.483337              912.408508      38.0      259.0
118         746.016968              762.931458      38.0      260.0
119         617.190857              630.918640      38.0      261.0
120         470.363831              493.396973      38.0      262.0
121         428.248840              429.999481      38.0      263.0
122         333.072662              356.559753      38.0      264.0
123         303.259430              282.100952      38.0      265.0
124         247.105286              274.491608      38.0      266.0
125         279.319916              297.353119      38.0      267.0
126         280.933289              303.076538      38.0      268.0
127         275.796692              276.219391      38.0      269.0
128        2919.751465             3124.591064      39.0      254.0
129        2586.268311             2300.221191      39.0      255.0
130        1825.946899             1725.342407      39.0      256.0
131        1453.338867             1475.911377      39.0      257.0
132        1187.619385             1166.599854      39.0      258.0
133         926.318298              957.809692      39.0      259.0
134         748.107666              731.922729      39.0      260.0
135         577.289062              573.204895      39.0      261.0
136         439.656647              446.799713      39.0      262.0
137         377.427307              396.012909      39.0      263.0
138         341.752502              352.090088      39.0      264.0
139         287.787567              295.501587      39.0      265.0
140         249.048508              254.907104      39.0     

In [15]:
elevation_data = np.array([np.array(i).flatten() for i in elevation.variables.values()]).T
elevation_dataframe = pd.DataFrame(elevation_data, columns=elevation.variables.keys())

In [16]:
elevation_dataframe.describe()

elevation_control  elevation_perturbation    latitude   longitude
count         144.000000              144.000000  144.000000  144.000000
mean          706.256714              710.712646   35.000000  261.500000
std           657.897095              662.597473    2.591001    4.625862
min            10.965302               17.772333   31.000000  254.000000
25%           226.564087              233.377026   33.000000  257.750000
50%           454.060379              438.399597   35.000000  261.500000
75%          1111.696045             1093.410065   37.000000  265.250000
max          2919.751465             3124.591064   39.000000  269.000000

## What other data files do I have?

In [15]:
%%bash

ls ../data/train

apcp_sfc_latlon_subset_19940101_20071231.nc
dlwrf_sfc_latlon_subset_19940101_20071231.nc
dswrf_sfc_latlon_subset_19940101_20071231.nc
pres_msl_latlon_subset_19940101_20071231.nc
pwat_eatm_latlon_subset_19940101_20071231.nc
spfh_2m_latlon_subset_19940101_20071231.nc
tcdc_eatm_latlon_subset_19940101_20071231.nc
tcolc_eatm_latlon_subset_19940101_20071231.nc
tmax_2m_latlon_subset_19940101_20071231.nc
tmin_2m_latlon_subset_19940101_20071231.nc
tmp_2m_latlon_subset_19940101_20071231.nc
tmp_sfc_latlon_subset_19940101_20071231.nc
ulwrf_sfc_latlon_subset_19940101_20071231.nc
ulwrf_tatm_latlon_subset_19940101_20071231.nc
uswrf_sfc_latlon_subset_19940101_20071231.nc


In [16]:
apcp_sfc =  netCDF4.Dataset('../data/train/apcp_sfc_latlon_subset_19940101_20071231.nc', 'r')

In [19]:
apcp_sfc.variables.keys()

odict_keys(['time', 'intTime', 'lat', 'lon', 'ens', 'fhour', 'intValidTime', 'Total_precipitation'])

In [20]:
np.array(apcp_sfc.variables['time'])

array([1700568., 1700592., 1700616., ..., 1823208., 1823232., 1823256.])

In [21]:
np.array(apcp_sfc.variables['intTime'])

array([1994010100, 1994010200, 1994010300, ..., 2007122900, 2007123000,
       2007123100], dtype=int32)

In [22]:
np.array(apcp_sfc.variables['lat'])

array([31., 32., 33., 34., 35., 36., 37., 38., 39.], dtype=float32)

In [23]:
np.array(apcp_sfc.variables['ens'])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16)

In [24]:
np.array(apcp_sfc.variables['fhour'])

array([12, 15, 18, 21, 24], dtype=int32)

In [25]:
apcp_sfc.variables

OrderedDict([('time', <class 'netCDF4._netCDF4.Variable'>
              float64 time(time)
                  long_name: Time
                  units: hours since 1800-01-01 00:00:00
                  axis: T
              unlimited dimensions: 
              current shape = (5113,)
              filling on, default _FillValue of 9.969209968386869e+36 used),
             ('intTime', <class 'netCDF4._netCDF4.Variable'>
              int32 intTime(time)
                  long_name: time as an integer (YYYYMMDDHH)
              unlimited dimensions: 
              current shape = (5113,)
              filling on, default _FillValue of -2147483647 used),
             ('lat', <class 'netCDF4._netCDF4.Variable'>
              float32 lat(lat)
                  long_name: Latitude
                  standard_name: latitude
                  units: degrees_north
                  actual_range: [31. 39.]
                  axis: Y
              unlimited dimensions: 
              current shape = 

I need to create 5-d arrays of each of the 1-d axes arrays and then flatten all of them. Then i can make a dataframe using my curent method.

In [4]:
meshes = np.meshgrid(apcp_sfc.variables['time'], 
                     apcp_sfc.variables['ens'], 
                     apcp_sfc.variables['fhour'], 
                     apcp_sfc.variables['lat'],
                     apcp_sfc.variables['lon'],
                     indexing='ij'
                    )

In [ ]:
flattened_data = [i.flatten() for i in meshes]
flattened_data.append(np.array(apcp_sfc.variables['Total_precipitation']).flatten())
data_as_dataframe = pd.DataFrame(flattened_data, columns=['Time', 'ensemble', 'forecast hours', 'lat', 'lon'])

In [5]:
xarray.open_dataarray?

In [7]:
xarray.open_dataset('../data/train/apcp_sfc_latlon_subset_19940101_20071231.nc')

<xarray.Dataset>
Dimensions:              (ens: 11, fhour: 5, lat: 9, lon: 16, time: 5113)
Coordinates:
  * time                 (time) datetime64[ns] 1994-01-01 1994-01-02 ...
  * lat                  (lat) float32 31.0 32.0 33.0 34.0 35.0 36.0 37.0 ...
  * lon                  (lon) float32 254.0 255.0 256.0 257.0 258.0 259.0 ...
  * ens                  (ens) int16 0 1 2 3 4 5 6 7 8 9 10
  * fhour                (fhour) timedelta64[ns] 0 days 12:00:00 ...
Data variables:
    intTime              (time) int32 ...
    intValidTime         (time, fhour) int32 ...
    Total_precipitation  (time, ens, fhour, lat, lon) float32 ...
Attributes:
    Conventions:  CF-1.0
    title:        Subset of data from 2nd-generation multi-decadal ensemble r...
    institution:  NOAA Earth System Research Laboratory (ESRL)
    source:       NCEP GFS v 9.01, T254L42.  Control initial conditions from ...
    references:   http://www.esrl.noaa.gov/psd/forecasts/reforecast2/index.html
    history:      Subs

In [24]:
a = np.array(list(apcp_sfc.variables.values())[-1])

In [25]:
np.shape(a)

(5113, 11, 5, 9, 16)

In [30]:
pd.MultiIndex?

In [34]:
len(apcp_sfc.variables.values())

8

In [49]:
indices = [0, 2, 3, 4, 5,]
levels = [np.array(list(apcp_sfc.variables.values())[i]) for i in indices]
#levels = [np.array(i).flatten() for i in list(apcp_sfc.variables.values())[0:-2]]

In [50]:
levels

[array([1700568., 1700592., 1700616., ..., 1823208., 1823232., 1823256.]),
 array([31., 32., 33., 34., 35., 36., 37., 38., 39.], dtype=float32),
 array([254., 255., 256., 257., 258., 259., 260., 261., 262., 263., 264.,
        265., 266., 267., 268., 269.], dtype=float32),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int16),
 array([12, 15, 18, 21, 24], dtype=int32)]

In [51]:
[np.shape(i) for i in levels]

[(5113,), (9,), (16,), (11,), (5,)]

In [54]:
labels = [list(apcp_sfc.variables.keys())[i] for i in indices]

In [61]:
a = np.array(list(apcp_sfc.variables.values())[-1])

In [62]:
a

array([[[[[0.000e+00, 0.000e+00, 0.000e+00, ..., 6.600e-01, 1.970e+00,
           5.500e-01],
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.220e+00, 8.500e+00,
           9.990e+00],
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 7.500e-01, 4.750e+00,
           1.219e+01],
          ...,
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 3.000e-02, 4.200e-01,
           7.500e-01],
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.000e-02, 3.100e-01,
           9.700e-01],
          [2.000e-02, 0.000e+00, 0.000e+00, ..., 0.000e+00, 7.000e-02,
           1.060e+00]],

         [[0.000e+00, 0.000e+00, 0.000e+00, ..., 4.200e-01, 3.300e-01,
           9.400e-01],
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.070e+00, 4.200e-01,
           9.600e-01],
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 1.540e+00, 7.400e-01,
           4.700e-01],
          ...,
          [0.000e+00, 0.000e+00, 0.000e+00, ..., 0.000e+00, 0.000e+00,
           1.000e-02],
          [0.000e+00, 0.000e

In [63]:
ls ../data

compressed_files/   sampleSubmission.csv  test/   train.csv
gefs_elevations.nc  station_info.csv      train/


In [64]:
train_data = pd.read_csv('../data/train.csv')

In [67]:
len(train_data.columns)

99

In [68]:
station_data = pd.read_csv('../data/station_info.csv')

In [69]:
station_data

stid      nlat       elon  elev
0   ACME  34.80833  -98.02325   397
1   ADAX  34.79851  -96.66909   295
2   ALTU  34.58722  -99.33808   416
3   APAC  34.91418  -98.29216   440
4   ARNE  36.07204  -99.90308   719
5   BEAV  36.80253 -100.53012   758
6   BESS  35.40185  -99.05847   511
7   BIXB  35.96305  -95.86621   184
8   BLAC  36.75443  -97.25452   304
9   BOIS  36.69256 -102.49713  1267
10  BOWL  35.17156  -96.63121   281
11  BREC  36.41201  -97.69394   352
12  BRIS  35.78050  -96.35404   239
13  BUFF  36.83129  -99.64101   559
14  BURB  36.63459  -96.81046   301
15  BURN  33.89376  -97.26918   228
16  BUTL  35.59150  -99.27059   520
17  BYAR  34.84970  -97.00330   345
18  CAMA  36.02866  -99.34652   589
19  CENT  34.60896  -96.33309   208
20  CHAN  35.65282  -96.80407   291
21  CHER  36.74813  -98.36274   362
22  CHEY  35.54615  -99.72790   694
23  CHIC  35.03236  -97.91446   328
24  CLAY  34.65657  -95.32596   186
25  CLOU  34.22321  -95.24870   221
26  COOK  35.68001  -94.84896   299
27  COPA  36.90987  -95.88553   250
28  DURA  33.92075  -96.32027   197
29  ELRE  35.54848  -98.03654   419
..   ...       ...        ...   ...
68  PERK  35.99865  -97.04831   292
69  PRYO  36.36914  -95.27138   201
70  PUTN  35.89904  -98.96038   589
71  REDR  36.35590  -97.15306   293
72  RETR  35.12275  -99.36001   538
73  RING  34.19365  -97.58812   283
74  SALL  35.43815  -94.79805   157
75  SEIL  36.19033  -99.04030   545
76  SHAW  35.36492  -96.94822   328
77  SKIA  36.41530  -96.03706   282
78  SLAP  36.59749 -100.26192   774
79  SPEN  35.54208  -97.34146   373
80  STIG  35.26527  -95.18116   173
81  STIL  36.12093  -97.09527   272
82  STUA  34.87642  -96.06982   256
83  SULP  34.56610  -96.95048   320
84  TAHL  35.97235  -94.98671   290
85  TALI  34.71070  -95.01152   204
86  TIPT  34.43972  -99.13755   387
87  TISH  34.33262  -96.67895   268
88  VINI  36.77536  -95.22094   236
89  WASH  34.98224  -97.52109   345
90  WATO  35.84185  -98.52615   517
91  WAUR  34.16775  -97.98815   283
92  WEAT  35.50830  -98.77509   538
93  WEST  36.01100  -94.64496   348
94  WILB  34.90092  -95.34805   199
95  WIST  34.98426  -94.68778   143
96  WOOD  36.42329  -99.41682   625
97  WYNO  36.51806  -96.34222   269

[98 rows x 4 columns]

In [70]:
sample_sub = pd.read_csv('../data/sampleSubmission.csv')

In [74]:
sample_sub['Date'][0]

20080101

In [77]:
list(train_data['Date'])[-1]

20071231

In [79]:
# Goal of this project: predict solar energy at 98 sites between 2008 and 2009 
# using data for the same between 1994 and 2007 along with models for solar energy
# across the wider geographic area

Goal of this project: predict solar energy at 98 sites between 2008 and 2009 
using data for the same between 1994 and 2007 along with models for solar energy
across the wider geographic area

I need to create a list of features for each solar site with training data.
One simple thing to do would be to 
1. find the GEFS model points which provide tri-linear interpolations for each mesonet point (based on lat, lon, elev)
2. find the indices of each GEFS point I need
3. for each property stored in a netcdf4 file, grab all the points of interest at each timestep
4. Calculate the interpolated value of each property for all the mesonet locations for each timestep and forecast time
5. create a dataframe from these data
6. build a model using the dataframes